### ISSUE TITLE
Exporting SCP from redfish is currently not using the right method

### ISSUE THREAD

**Issue by felixs88** [dell/omsdk#1]
# QwikContext
For exporting SCP using redfish (and local share), we are using `_scp_export_to_local_share_redfish`, this method is not defined in https://github.com/dell/omsdk/blob/5d2ead24b10fd213fb32d5bb9a8a8fb6ef8be2a2/omdrivers/lifecycle/iDRAC/iDRACConfig.py#L2372

# Details
`_scp_export_to_local_share_redfish` is actually defined in https://github.com/dell/omsdk/blob/5d2ead24b10fd213fb32d5bb9a8a8fb6ef8be2a2/omdrivers/lifecycle/iDRAC/iDRACConfig.py#L197 which is as I understand it is for WsMan only, meaning that when we instantiate PREDFISH, we're getting commands from https://github.com/dell/omsdk/blob/5d2ead24b10fd213fb32d5bb9a8a8fb6ef8be2a2/omdrivers/lifecycle/iDRAC/iDRACConfig.py#L2372 which lacks that method.

The call for that method is here: https://github.com/dell/omsdk/blob/master/omdrivers/lifecycle/iDRAC/iDRACConfig.py#L4964

That comment seems to imply that actions are ongoing around these methods: https://github.com/dell/omsdk/blob/master/omdrivers/lifecycle/iDRAC/iDRACConfig.py#L2064

# Repro Steps
Use https://github.com/dell/Dell-EMC-Ansible-Modules-for-iDRAC with the following configuration:

```
---
- hosts: oob
  name: Export Server Configuration Profile to local folder
  connection: local
  gather_facts: False

  tasks:
    - name: Export Server Configuration Profile to local folder
      dellemc_export_server_config_profile:
        idrac_ip:        "{{ inventory_hostname }}"
        idrac_user:      "root"
        idrac_pwd:       'password'
        share_name:      "{{ playbook_dir }}"
        scp_components:  "ALL"
        job_wait:        "True"
      tags:
        - scp_components_bios
      delegate_to: localhost
```
It'll return an empty dict that won't be written to the file you specify in `share_name`.

# Impact
I can't export SCP to local file, import seems to be impacted as well if I read it correctly.

# NeedBy
ASAP, happy to help, I can probably copy/move the methods over to https://github.com/dell/omsdk/blob/5d2ead24b10fd213fb32d5bb9a8a8fb6ef8be2a2/omdrivers/lifecycle/iDRAC/iDRACConfig.py#L2372 but I'm not sure if their absence is intended or n

# Severity
Export is not working so Major.

**Comment by felixs88** [comment]
@xiu, We have to rebuild the omsdk repository, So we are recreating your issue.

@anupamaloke response,

> thanks for bringing this to our attention. We will take a look into this issue and fix it. In the meanwhile, I can confirm that export and import using redfish are working fine for 14G servers. Could you please let us know the iDRAC firmware against which you are facing this issue?

**Comment by rajeevarakkal** [comment]
@xiu Closing this as of now as there is no update since long
