### ISSUE TITLE
"def _get_redfish_jobid(self, headers):" defined twice

### ISSUE THREAD

**Issue by huornlmj** [dell/omsdk#15]
https://github.com/dell/omsdk/blob/756d7ab1b4938dafac6da3be73df91a0f575b560/omsdk/http/sdkwsmanbase.py#L400

`_get_redfish_jobid` is already defined on line 244

**Comment by jagadeeshnv** [comment]
Thanks @huornlmj we will fix it soon

**Comment by jagadeeshnv** [comment]
Hi @huornlmj 
Fixed with latest, https://github.com/dell/omsdk/tree/v.1.2.434
Kindly check
