### ISSUE TITLE
OMSDK incompatible with Python 3.12

### ISSUE THREAD

**Issue by lestercheung** [dell/omsdk#43]
# Problem
OMSDK does not work with Python 3.12

# Details
It's trying to import the `imp` module which has been removed from 3.12.

# Repro Steps
Works in 3.9:
```
(py3.9) ➜  ~ python3.9
Python 3.9.6 (default, Dec  7 2023, 05:42:47)
[Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from omsdk.sdkinfra import sdkinfra
>>>
```

Not working in 3.12:
```
(py3) ➜ ~ python 
Python 3.12.1 (main, Dec  7 2023, 20:45:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import omsdk
>>> from omsdk.sdkinfra import sdkinfra
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bugreport/.local/py3/lib/python3.12/site-packages/omsdk/sdkinfra.py", line 24, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
>>>
```

# Impact
The [dellemc_idrac_storage_volume](https://github.com/dell/dellemc-openmanage-ansible-modules/blob/collections/docs/modules/dellemc_idrac_storage_volume.rst) Ansible module depends on this.

# NeedBy
Update sdkinfra.py to use importlib?

# Severity
This prevents any organizations to upgrade to Python3.12 on machines managing Dell machines using Ansible.

**Comment by thebeanogamer** [comment]
I'm trying to resolve this as it's causing build failures in Fedora. The Python docs (<https://docs.python.org/3/whatsnew/3.12.html#imp>) have a replacement for `imp.load_source` but intentionally do not have a replacement for `imp.load_compiled` as it was never documented behaviour.

Still trying to wrap my head around why `omsdk` is manually manipulating imports in the way it is. Will update here if I can find a workaround.

**Comment by kitos9112** [comment]
Hitting this same issue here too. Not just the aforementioned module but ` dellemc.openmanage.idrac_firmware_info`

We'd appreciate any update

**Comment by anupamaloke** [comment]
This is currently being worked on by the Dell team and will be addressed in the May month release.
